# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
parameters:
    app.session_idle_timeout: 7200

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Model/'
            - '../src/DependencyInjection/'

    App\Service\IoTag\IoTagEncoder:
        arguments:
            - !tagged_iterator app.io_tag_encoder

    League\CommonMark\CommonMarkConverter:

    App\Service\Image\ResponsiveImageTag\Interface\ResponsiveImageTagInterface:
        class: App\Service\Image\ResponsiveImageTag\ResponsiveImageTag

    App\Service\ErrorLogger\Interface\ErrorLoggerInterface:
        class:  App\Service\ErrorLogger\EmailNotification

    App\Service\Navigation\NavigationService:
        arguments:
            $navigationItems: []

    App\Service\Navigation\Interface\NavigationServiceInterface: '@App\Service\Navigation\NavigationService'

    App\Service\DataCollector\Interface\DataCollectorServiceInterface:
        class: App\Service\DataCollector\DataCollectorService
        arguments:
            - !tagged_iterator app.data_collector
